version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: user_app
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; sh start_api.sh'
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user_app:user_app@db:5432/user_app
    depends_on:
      - db
      - migration

  db:
    image: "postgres:13-alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_DB=user_app
      - POSTGRES_USER=user_app
      - POSTGRES_PASSWORD=user_app

  migration:
    image: user_app
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python -m alembic upgrade head'
    volumes:
      - .:/app/
    depends_on:
      - db

volumes:
  postgres_data: