version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=service_name_of_db
      - POSTGRES_DB=database_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    depends_on:
      - db
    restart: always
    networks:
      - practice

  db:
    image: "postgres"
    environment:
      - POSTGRES_HOST=service_name_of_db
      - POSTGRES_DB=database_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    env_file:
      - ./.env
    restart: always
    networks:
      - practice

networks:
  - practice