import setuptools


setuptools.setup(
    name='user_transaction_app',
    packages=setuptools.find_packages(),
    version='0.1',
    description='Some User Transaction API',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='',
    author='Abylay',
    author_email='',
    classifiers=[
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
    ],
    # project_urls={
    #     'Repository': '',
    # },
    python_requires='>=3.8,<4.0',
    install_requires=[
        'aiohttp==3.8.1',
        'alembic==1.7.7',
        'asgiref==3.5.0',
        'confboy==1.1.2',
        'databases==0.5.5',
        'fastapi==0.75.2',
        'loguru==0.6.0',
        'psutil==5.9.0',
        'setproctitle==1.2.3',
        'sqlalchemy==1.4.43',
        'sqlalchemy_utils==0.38.2',
        'uvicorn==0.17.6',
        'tzlocal==4.2',
        'asyncmy==0.2.3',
        'bcrypt==3.2.0',
        'aiosmtplib==1.1.6',
        'orjson==3.6.8',
        'psycopg2==2.9.3',
        'asyncpg==0.25.0',
        'aiosqlite==0.17.0'
    ],
    extras_require={
        'dev':  [
            'flake8-commas==2.1.0',
            'flake8-import-order==0.18.1',
            'flake8-quotes==3.3.1',
            'flake8==4.0.1',
            'ipdb==0.13.9',
            'mypy==0.942',
            'pep8-naming==0.12.1',
            'types-Jinja2==2.11.9',
            'types-aiofiles==0.8.8',
            'types-click==7.1.8',
            'types-orjson==3.6.2',
            'types-python-dateutil==2.8.11',
            'types-pytz==2021.3.6',
            'types-requests==2.27.19',
            'types-ujson==4.2.1',
        ],
        'test': [
            'async-asgi-testclient==1.4.10',
            'pytest-asyncio==0.18.3',
            'pytest-cov==3.0.0',
            'pytest-freezegun==0.4.2',
            'pytest-mock==3.7.0',
            'pytest==7.1.1',
        ],
    },
    entry_points={
        'console_scripts': [
            'user_app=user_app.__main__:main',
        ],
    },
)
